name: isolate_pool_2
description: Just like a thread pool, but with isolates. The package allows creating up-and-running isolates that can accept requests and do heavy lifting outside main isolate
version: 1.0.7
homepage: https://github.com/maxim-saplin/isolate_pool

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test:
  lints: 
